# Generated by Django 5.0.6 on 2024-06-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('car_class', models.CharField(max_length=50)),
                ('basic_features', models.JSONField()),
                ('additional_features', models.JSONField()),
                ('year_of_manufacturing', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
        ),
    ]
