# Generated by Django 5.0.6 on 2024-06-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
