# Generated by Django 5.0.6 on 2024-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_image_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='history',
            field=models.TextField(blank=True),
        ),
    ]
