# Generated by Django 5.0.6 on 2024-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='history',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
