# Generated by Django 5.0.6 on 2024-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='history',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
